### ISSUE TITLE
Java 11 needed

### ISSUE THREAD

**Issue by erfont** [GAIGResearch/TabletopGames#120]
Hi, 
the project has a dependency in SolutionEvaluator that needs Java 11 at least. Trying to build it with Java 8 got me this error:

java: cannot access evodef.SolutionEvaluator
  bad class file: .../.m2/repository/com/github/hopshackle/NTBEA/0.2/NTBEA-0.2.jar!/evodef/SolutionEvaluator.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.  

Please update that info on the setting up section. 

Otherwise really great framework. Congrats!

**Comment by hopshackle** [comment]
Thanks for pointing that out!

We'll get that sorted (ideally by amending the problematic library dependency).

**Comment by hopshackle** [comment]
Dependency now removed. The whole framework should be be restored to Java 8 compatibility, including its transitive dependencies.
