### ISSUE TITLE
Query about configurations of Pandemic competion

### ISSUE THREAD

**Issue by youpengzhao** [GAIGResearch/TabletopGames#181]
We intend to participate in the COG2022 competition: Pandemic. We want to know whether the configuration of this competition has been determined. For example, how many players are there in one game and whether their roles are fixed or random assigned. Also, is there a evaluation program to give score to the entry? We think this is important as it will help the training of AIs if we can know the true scores.

**Comment by youpengzhao** [comment]
Also, as this game can be played by 2~4 players, I hope to know how many players will be used in the competition.

**Comment by martinballa** [comment]
We are still working on the configurations but hopefully, we can release them soon. 
Some configurations are going to have 2 players while some are going to have 4 and we pick the roles for the players (can be any role).
The evaluation is going to be relative to the other entries, we are going to assign points for the best entries on each evaluation configuration. The winner is going to be the entry that has the highest overall score across all configurations. You can read about the tie breaks and the evaluation on this page: http://www.tabletopgames.ai/competition/cog2022/
