### ISSUE TITLE
Investigate feasibility of generating the list of actions, as well as checking viability of actions returned by agents? (if not index)

### ISSUE THREAD

**Issue by rdgain** [GAIGResearch/TabletopGames#40]

**Comment by hopshackle** [comment]
I have a similar issue in Dominion. For example with 4 Buys and a spend of 10 money, and 13 possible cards you have a combinatorial number of actions (up to 715 in this case). I use exactly the approach recommended by Alex - make this a sequential decision of one buy after the other.

In other cases I have actions with multiple stages - for example a Cellar allows you to discard any number of cards from your hand (another combinatorial issue), and then draw a number of new cards equal to the number discarded. For this I have implemented a DominionExtendedAction that keeps control of the ActionState in an encapsulated fashion without bloating the GameState/ForwardModel. Have a look in the Dominion branch, and see if you think there is something there that could be incorporated into the core.

**Comment by hopshackle** [comment]
Closing this issue as we now have several games that do exactly this, splitting up the decision into distinct chunks.
